insert into sibes_menus values 
(36,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,35),
(8,6,'Carousels','/base/carousels',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,9),
(9,6,'Collapses','/base/collapses,NULL','icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,9),
(10,6,'Forms','/base/forms',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,9),
(11,6,'Navbars','/base/navbars',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,9),
(13,6,'Popovers','/base/popovers',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(14,6,'Progress','/base/progress',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(15,6,'Switches','/base/switches',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(16,6,'Tables','/base/tables',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(7,6,'Tabs','/base/tabs',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(18,6,'Tooltips','/base/tooltips',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(20,19,'Buttons','/buttons/buttons',NULL,'icon-cursor',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(21,19,'Dropdowns','/buttons/dropdowns',NULL,'icon-cursor',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(22,19,'Brand Buttons','/buttons/brand-buttons',NULL,'icon-cursor',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(25,24,'CoreUI Icons','/icons/coreui-icons',NULL,'icon-star','NEW','success',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(26,24,'Flags','/icons/flags',NULL,'icon-star',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(27,24,'Font Awesome','/icons/font-awesome',NULL,'icon-star',4.7,'secondary',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(28,24,'Simple Line Icons','/icons/simple-line-icons',NULL,'icon-star',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(30,29,'Alerts','/notifications/alerts',NULL,'icon-bell',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(31,29,'Badges','/notifications/badges',NULL,'icon-bell',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(32,29,'Modal','/notifications/modals',NULL,'icon-bell',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,12),
(35,0,'Download CoreUI','http://coreui.io/angular/',NULL,'icon-cloud-download',NULL,NULL,NULL,'success','"target": "_blank"','"rel": "noopener"',NULL,'mt-auto',NULL,NULL,NULL,NULL,NULL,NULL,true,36),
(19,6,'Buttons','/buttons',NULL,'icon-cursor',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(23,6,'Charts','/charts',NULL,'icon-pie-chart',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(24,6,'Icons','/icons',NULL,'icon-star',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(29,6,'Notifications','/notifications',NULL,'icon-bell',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,11),
(37,0,'Reportes','/reportes',NULL,'icon-layers','NEW','info',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,7),
(6,0,'Compo. Boostrap','/base',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,9),
(39,6,'Temas','/theme',NULL,'icon-drop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,12),
(40,39,'theme','/theme/colors',NULL,'icon-drop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,12),
(41,39,'typografy','/theme/typography',NULL,'icon-drop',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,12),
(42,6,'Widgets','/widgets',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,12),
(12,6,'Pagination','/base/paginations',NULL,'icon-puzzle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,10),
(1,0,'Principal','/sibes/principal',NULL,'icon-speedometer','Home','warning',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,1),
(2,0,'Beneficio Escolar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,true,2),
(3,0,'Facturas','/sibes/facturas',NULL,'icon-docs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,3),
(45,0,'Beneficiarios','sibes/beneficiarios',NULL,'icon-graduation',NULL,'warning',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,3),
(46,0,'Inscripciones','sibes/inscripciones',NULL,'icon-pencil',NULL,'warning',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,3),
(4,0,'Instituciones','/sibes/colegios',NULL,'icon-home',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,4),
(43,37,'Hijos de Trabajadores','/sibes/hijostrabajadores',NULL,'icon-people',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,7),
(44,0,'Mensualidades','/sibes/mensualidades',NULL,'icon-calendar',NULL,'info',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,true,3);

insert into sibes_menus_usuarios
select idmenu, 'matlux', true,true,true,true from sibes_menus